DEMO01 = "01 - Initialization/"
DEMO02 = "02 - Resources/"
DEMO03 = "03 - Input/"
DEMO04 = "04 - Screen Settings/"
DEMO05 = "05 - Primitives/"
DEMO06 = "06 - Text/"
DEMO07 = "07 - Sprites"
DEMO08 = "08 - Sprite Engine/"
DEMO09 = "09 - Sprite Engine(Classes)/"
DEMO10 = "10 - Tiles/"
DEMO11 = "11 - Grid/"
DEMO12 = "12 - Render into Texture/"
DEMO13 = "13 - Particles/"
DEMO14 = "14 - Sound/"
DEMO15 = "15 - Video/"
DEMO16 = "16 - Physics/"

all:
	make -C $(DEMO01)
	make -C $(DEMO02)
	make -C $(DEMO03)
	make -C $(DEMO04)
	make -C $(DEMO05)
	make -C $(DEMO06)
	make -C $(DEMO07)
	make -C $(DEMO08)
	make -C $(DEMO09)
	make -C $(DEMO10)
	make -C $(DEMO11)
	make -C $(DEMO12)
	make -C $(DEMO13)
	make -C $(DEMO14)
	make -C $(DEMO15)
	make -C $(DEMO16)

linux32:
	make -C $(DEMO01) linux32
	make -C $(DEMO02) linux32
	make -C $(DEMO03) linux32
	make -C $(DEMO04) linux32
	make -C $(DEMO05) linux32
	make -C $(DEMO06) linux32
	make -C $(DEMO07) linux32
	make -C $(DEMO08) linux32
	make -C $(DEMO09) linux32
	make -C $(DEMO10) linux32
	make -C $(DEMO11) linux32
	make -C $(DEMO12) linux32
	make -C $(DEMO13) linux32
	make -C $(DEMO14) linux32
	make -C $(DEMO15) linux32
	make -C $(DEMO16) linux32

win32:
	make -C $(DEMO01) win32
	make -C $(DEMO02) win32
	make -C $(DEMO03) win32
	make -C $(DEMO04) win32
	make -C $(DEMO05) win32
	make -C $(DEMO06) win32
	make -C $(DEMO07) win32
	make -C $(DEMO08) win32
	make -C $(DEMO09) win32
	make -C $(DEMO10) win32
	make -C $(DEMO11) win32
	make -C $(DEMO12) win32
	make -C $(DEMO13) win32
	make -C $(DEMO14) win32
	make -C $(DEMO15) win32
	make -C $(DEMO16) win32

win64:
	make -C $(DEMO01) win64
	make -C $(DEMO02) win64
	make -C $(DEMO03) win64
	make -C $(DEMO04) win64
	make -C $(DEMO05) win64
	make -C $(DEMO06) win64
	make -C $(DEMO07) win64
	make -C $(DEMO08) win64
	make -C $(DEMO09) win64
	make -C $(DEMO10) win64
	make -C $(DEMO11) win64
	make -C $(DEMO12) win64
	make -C $(DEMO13) win64
	make -C $(DEMO14) win64
	make -C $(DEMO15) win64
	make -C $(DEMO16) win64

macosx:
	make -C $(DEMO01) macosx
	make -C $(DEMO02) macosx
	make -C $(DEMO03) macosx
	make -C $(DEMO04) macosx
	make -C $(DEMO05) macosx
	make -C $(DEMO06) macosx
	make -C $(DEMO07) macosx
	make -C $(DEMO08) macosx
	make -C $(DEMO09) macosx
	make -C $(DEMO10) macosx
	make -C $(DEMO11) macosx
	make -C $(DEMO12) macosx
	make -C $(DEMO13) macosx
	make -C $(DEMO14) macosx
	make -C $(DEMO15) macosx
	make -C $(DEMO16) macosx

macosx_uni:
	make -C $(DEMO01) macosx_uni
	make -C $(DEMO02) macosx_uni
	make -C $(DEMO03) macosx_uni
	make -C $(DEMO04) macosx_uni
	make -C $(DEMO05) macosx_uni
	make -C $(DEMO06) macosx_uni
	make -C $(DEMO07) macosx_uni
	make -C $(DEMO08) macosx_uni
	make -C $(DEMO09) macosx_uni
	make -C $(DEMO10) macosx_uni
	make -C $(DEMO11) macosx_uni
	make -C $(DEMO12) macosx_uni
	make -C $(DEMO13) macosx_uni
	make -C $(DEMO14) macosx_uni
	make -C $(DEMO15) macosx_uni
	make -C $(DEMO16) macosx_uni

clean:
	make -C $(DEMO01) clean
	make -C $(DEMO02) clean
	make -C $(DEMO03) clean
	make -C $(DEMO04) clean
	make -C $(DEMO05) clean
	make -C $(DEMO06) clean
	make -C $(DEMO07) clean
	make -C $(DEMO08) clean
	make -C $(DEMO09) clean
	make -C $(DEMO10) clean
	make -C $(DEMO11) clean
	make -C $(DEMO12) clean
	make -C $(DEMO13) clean
	make -C $(DEMO14) clean
	make -C $(DEMO15) clean
	make -C $(DEMO16) clean
